### ISSUE TITLE
loss of new posts

### ISSUE THREAD

**Issue by searoso** [sandstormports/wordpress-sandstorm#37]
**Very often** after making up a post I see following message, and I should **redo complete post**! There was a case I get a lot of it back with a note that it found more information in my browser than in the draft. But most of the time I just left without anything. Could it be solved with more frequent draft saving inside WP?

> The link you followed has expired.
> 
> [Please try again.](https://ui-79a8295d1a3ccf8c91d70358a1feb388.oasis.sandstorm.io/wp-admin/post-new.php)

Will keep an eye on it, if it occurs after creating a post in the window which was around for a long time.

Maybe a workaround will be to refresh the page before starting a new post.

**Comment by searoso** [comment]
If it will be of assistance, I just got this _error_ creating a page. _It was **not inside** of Sandstorm._

```
ERROR: The server threw an exception. Details:

(remote):0: failed: remote exception: remote exception: remote exception: Error: Requested session that no longer exists, and timed out waiting for client to restore it. This can happen if you have opened an app's content in a new window and then closed it in the UI. If you see this error *inside* the Sandstorm UI, please report a bug and describe the circumstances of the error.
    at Meteor.setTimeout (server/gateway-router.js:287:18)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at packages/meteor.js:620:25
    at runWithEnvironment (packages/meteor.js:1356:24)
 => awaited here:
    at Promise.await (/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at inMeteor (server/gateway-router.js:268:23)
    at inMeteorInternal (imports/server/async-helpers.js:24:17)
    at Meteor.bindEnvironment.callback (imports/server/async-helpers.js:12:3)
    at runWithEnvironment (packages/meteor.js:1356:24)
    at packages/meteor.js:1369:14
    at Promise (imports/server/async-helpers.js:22:5)
    at new Promise (<anonymous>)
    at inMeteor (imports/server/async-helpers.js:21:10)
    at GatewayRouterImpl.openUiSession (server/gateway-router.js:266:12)
    at /node_modules/capnp.js:174:21
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
stack: 7f4900 4676f0 458bb0 459008 458a9d 57dd91 468140 5681c0 569530 5678e0 680e60 67bd00 5678e0 435e10 42e1e0 4b5920 4b8b70
```

**Comment by searoso** [comment]
I suppose it's kind of problem with background draft saving. In right bottom corner of editor system reports _draft saving..._, but without Sandstorm it usually blazing fast. In Oasis it can't save draft in the bg.

**Comment by JamborJan** [comment]
Thanks for taking the time to open this and also the other issues you posted. I’ll take a look at this. As I’m pretty busy right now I cannot promise when I’ll have a solution to this. But I’ll do my best to include fixes for all the issues you have posted.

Again thanks for contributing.

**Comment by JamborJan** [comment]
Unfortunately I was not able to do anything here yet. Due to many ongoing projects I’ve very limited resources. Nevertheless: it’s important for me to keep this alive and I’ll do my best to start working on this during the next weeks.
